# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

from os import path


class myPlainTextEdit(QtWidgets.QPlainTextEdit):
    """ 自定义的PlainTextEdit类,重新改写了原本的dropEvent函数
    使得拖拽进区域后显示的文件路径不包含file:///,并且每次新的拖拽都
    会另起一行显示文件路径
    D:/B站视频/video1.MP4
    D:/B站视频/video2.MP4
    D:/B站视频/video3.MP4 """
    def dropEvent(self, event):
        temp = event.mimeData().urls()[0].path()
        filename = temp[1:].strip()
        _, suffix = path.splitext(filename) # .mp4
        presentText = self.toPlainText()
        if not presentText or suffix in presentText:
            self.appendPlainText(filename)

class myPlainTextEdit2(QtWidgets.QPlainTextEdit):
    """ 自定义的PlainTextEdit类,重新改写了原本的dropEvent函数
    使得拖拽进区域后显示的文件路径不包含file:///,并且每次新的拖拽都
    会另起一行显示文件路径
    D:/B站视频/video1.MP4
    D:/B站视频/video2.MP4
    D:/B站视频/video3.MP4 """
    def dropEvent(self, event):
        temp = event.mimeData().urls()[0].path()
        filename = temp[1:].strip()
        self.appendPlainText(filename)
class myLabel(QtWidgets.QLabel):
    """ 自定义Label类,重新改写了原本的dragEnterEvent和dropEvent函数
    使得新的Label类接受拖拽操作,文件路径将被显示(注意设置setAcceptDrops为True) """
    def dragEnterEvent(self, event):
        event.acceptProposedAction()
    
    
    def dropEvent(self, event):
        temp = event.mimeData().urls()[0].path()
        filename = temp[1:].strip()
        self.setText(filename)
        event.accept()


class Ui_myWindow(object):
    """ Ui_myWindow并非是窗体本身,但提供了绝大多数窗口部件
    的命名空间,在主程序main.py中写交互操作 """
    def setupUi(self, myWindow): 
        # 设置主窗口大小,标题,字体大小...
        myWindow.setObjectName("myWindow")
        myWindow.resize(860, 750)
        myWindow.setMinimumSize(QtCore.QSize(880, 800))
        myWindow.setWindowTitle('BilibiliDownLoad')
        font = QtGui.QFont()
        font.setPointSize(12)
        myWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/SVG/图标.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        myWindow.setWindowIcon(icon)
        # 设置中心容器
        self.centralWidget = QtWidgets.QWidget(myWindow)
        self.centralWidget.setObjectName("centralWidget")
        # 设置中心容器的箱布局为水平
        self.centralHLayout0 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.centralHLayout0.setObjectName("centralHLayout0")
        # 引入垂直箱布局
        self.centralVLayout = QtWidgets.QVBoxLayout()
        self.centralVLayout.setObjectName("centralVLayout")
        # 引入水平箱布局
        self.centralHLayout1 = QtWidgets.QHBoxLayout()
        self.centralHLayout1.setObjectName("centralHLayout1")
        # 引入输入BV号的说明label
        self.labelBV = QtWidgets.QLabel(self.centralWidget)
        self.labelBV.setObjectName("labelBV")
        # 将说明label放入水平布局中
        self.centralHLayout1.addWidget(self.labelBV)
        # 引入输入BV号的文字框lineText
        self.lineTextBV = QtWidgets.QLineEdit(self.centralWidget)
        self.lineTextBV.setObjectName("lineTextBV")
        # 将文字输入框放入水平布局
        self.centralHLayout1.addWidget(self.lineTextBV)
        # 引入确定按钮
        self.okPushButton = QtWidgets.QPushButton(self.centralWidget)
        self.okPushButton.setObjectName("okPushButton")
        # 放入到水平布局
        self.centralHLayout1.addWidget(self.okPushButton)
        # 把上述水平布局放入垂直布局
        self.centralVLayout.addLayout(self.centralHLayout1)
        # 引入分页容器QTabWidget,并设置字体为15和鼠标属性,分页样式
        self.partWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.partWidget.setFont(font)
        self.partWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.partWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.partWidget.setObjectName("partWidget") # 后面将此容器放入垂直布局self.centralVLayout
        # 然后将垂直布局self.centralVLayout放入水平布局
        # 设置容器储存视频信息
        self.tabInfo = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabInfo.setFont(font)
        self.tabInfo.setObjectName("tabInfo")
        # 设置此容器的布局为水平箱布局
        self.tabInfoHLayout = QtWidgets.QHBoxLayout(self.tabInfo)
        self.tabInfoHLayout.setObjectName("tabInfoHLayout")
        # 引入子容器tabInfoWidget
        self.tabInfoWidget = QtWidgets.QWidget(self.tabInfo)
        self.tabInfoWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabInfoWidget.setObjectName("tabInfoWidget")
        # 在子容器引入垂直分布
        self.tabinfoVLayout = QtWidgets.QVBoxLayout(self.tabInfoWidget)
        self.tabinfoVLayout.setObjectName("tabinfoVLayout")
        # 引入表格infochart
        self.infoChart = QtWidgets.QTableWidget(self.tabInfoWidget)
        self.infoChart.setMaximumSize(QtCore.QSize(278, 300))
        self.infoChart.setFrameShape(QtWidgets.QFrame.Box)
        self.infoChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoChart.setMidLineWidth(2)
        self.infoChart.setProperty("showDropIndicator", True)
        self.infoChart.setAlternatingRowColors(True)
        self.infoChart.setShowGrid(True)
        self.infoChart.setGridStyle(QtCore.Qt.DashDotLine)
        self.infoChart.setWordWrap(True)
        self.infoChart.setCornerButtonEnabled(True)
        self.infoChart.setObjectName("infoChart")
        self.infoChart.setColumnCount(1)
        self.infoChart.setRowCount(7)
        # 上述👆设置了表格的基本属性
        # 设置列表头
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setVerticalHeaderItem(6, item)
        # 设置行表头
        item = QtWidgets.QTableWidgetItem()
        self.infoChart.setHorizontalHeaderItem(0, item)
        self.infoChart.horizontalHeader().setVisible(False) # 隐藏水平表头
        # 水平/列表头的宽度设置
        self.infoChart.horizontalHeader().setDefaultSectionSize(220)
        self.infoChart.verticalHeader().setDefaultSectionSize(42)
        # 将表放入前面的垂直布局
        self.tabinfoVLayout.addWidget(self.infoChart)
        # 引入描述性的标签
        self.labelDesc = QtWidgets.QLabel(self.tabInfoWidget)
        self.labelDesc.setMaximumSize(QtCore.QSize(278, 38))
        self.labelDesc.setObjectName("labelDesc")
        # 放入垂直布局
        self.tabinfoVLayout.addWidget(self.labelDesc)
        # 引入描述展览板,并且保护其预设的大小
        self.DesctextBrowser = QtWidgets.QTextBrowser(self.tabInfoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DesctextBrowser.sizePolicy().hasHeightForWidth())
        self.DesctextBrowser.setSizePolicy(sizePolicy)
        self.DesctextBrowser.setMaximumSize(QtCore.QSize(278, 16777215))
        self.DesctextBrowser.setLineWrapColumnOrWidth(25)
        self.DesctextBrowser.setReadOnly(False)
        self.DesctextBrowser.setObjectName("DesctextBrowser")
        # 放入垂直布局
        self.tabinfoVLayout.addWidget(self.DesctextBrowser)
        # 将子容器放入水平布局
        self.tabInfoHLayout.addWidget(self.tabInfoWidget)
        # 引入美图标签页👩
        # 设置尺寸扩展
        self.labelPic = QtWidgets.QLabel(self.tabInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPic.sizePolicy().hasHeightForWidth())
        self.labelPic.setSizePolicy(sizePolicy)
        self.labelPic.setMinimumSize(QtCore.QSize(493, 0))
        self.labelPic.setText("")
        # 引入唐莉佳美图
        self.labelPic.setPixmap(QtGui.QPixmap(":/PNG/tlj1.png"))
        self.labelPic.setScaledContents(True)
        self.labelPic.setObjectName("labelPic")
        # 加入水平布局
        self.tabInfoHLayout.addWidget(self.labelPic)
        # 引入图标
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/SVG/信息.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # 加入分页
        self.partWidget.addTab(self.tabInfo, icon, "")
        # 引入第二个视频分页
        self.tabVideo = QtWidgets.QWidget()
        self.tabVideo.setObjectName("tabVideo")
        # 设置为垂直布局
        self.tabVideoVLayout = QtWidgets.QVBoxLayout(self.tabVideo)
        self.tabVideoVLayout.setContentsMargins(-1, 11, -1, -1)
        self.tabVideoVLayout.setObjectName("tabVideoVLayout")
        # 引入放置弹幕选择按钮的水平布局
        self.tabVideoHLayout = QtWidgets.QHBoxLayout()
        self.tabVideoHLayout.setContentsMargins(-1, 0, -1, -1)
        self.tabVideoHLayout.setObjectName("tabVideoHLayout")
        # 引入单选择按钮XML
        self.radButtonXML = QtWidgets.QRadioButton(self.tabVideo)
        self.radButtonXML.setChecked(True)
        self.radButtonXML.setObjectName("radButtonXML")
        self.tabVideoHLayout.addWidget(self.radButtonXML)
        # 引入单选择按钮ASS
        self.radButtonASS = QtWidgets.QRadioButton(self.tabVideo)
        self.radButtonASS.setObjectName("radButtonASS")
        self.tabVideoHLayout.addWidget(self.radButtonASS)
        # 引入对线程标签
        self.labelThreads = QtWidgets.QLabel(self.tabVideo)
        self.labelThreads.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelThreads.setObjectName("labelThreads")
        self.tabVideoHLayout.addWidget(self.labelThreads)
        # 引入数值选用框
        self.spinBoxThreads = QtWidgets.QSpinBox(self.tabVideo)
        self.spinBoxThreads.setMinimum(3)
        self.spinBoxThreads.setMaximum(10)
        self.spinBoxThreads.setProperty("value", 3)
        self.spinBoxThreads.setObjectName("spinBoxThreads")
        self.tabVideoHLayout.addWidget(self.spinBoxThreads)
        self.tabVideoHLayout.setStretch(0, 2)
        self.tabVideoHLayout.setStretch(1, 2)
        self.tabVideoHLayout.setStretch(2, 3)
        self.tabVideoHLayout.setStretch(3, 1)
        # 将水平布局加入垂直布局
        self.tabVideoVLayout.addLayout(self.tabVideoHLayout)
        # 引入滚动区域
        self.scrollArea = QtWidgets.QScrollArea(self.tabVideo)
        self.scrollArea.setMinimumSize(QtCore.QSize(769, 441))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # 在里面构建容器
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 806, 496))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # 设置水平布局
        self.scrollVLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollVLayout.setObjectName("scrollVLayout")
        # 引入图片标签
        self.labelgkd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelgkd.setText("")
        self.labelgkd.setPixmap(QtGui.QPixmap(":/JPG/gkd.jpg"))
        self.labelgkd.setScaledContents(True)
        self.labelgkd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelgkd.setObjectName("labelgkd")
        # 加入布局
        self.scrollVLayout.addWidget(self.labelgkd)
        # 设置和内部构建容器的关联
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabVideoVLayout.addWidget(self.scrollArea)
        # 引入全部下载按键
        self.pushButtonAllDownLoad = QtWidgets.QPushButton(self.tabVideo)
        self.pushButtonAllDownLoad.setObjectName("pushButtonAllDownLoad")
        self.tabVideoVLayout.addWidget(self.pushButtonAllDownLoad)
        # 设置分页的图标
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/SVG/视频.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.partWidget.addTab(self.tabVideo, icon1, "")
        # 引入第三个图片分页
        self.tabpicture = QtWidgets.QWidget()
        self.tabpicture.setObjectName("tabpicture")
        self.groupBoxPic = QtWidgets.QGroupBox(self.tabpicture)
        self.groupBoxPic.setGeometry(QtCore.QRect(10, 10, 811, 591))
        self.groupBoxPic.setObjectName("groupBoxPic")
        self.groupBoxPicHLayout = QtWidgets.QHBoxLayout(self.groupBoxPic)
        self.groupBoxPicHLayout.setObjectName("groupBoxPicHLayout")
        self.toolBox = QtWidgets.QToolBox(self.groupBoxPic)
        self.toolBox.setMaximumSize(QtCore.QSize(145, 16777215))
        self.toolBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBox.setFrameShape(QtWidgets.QFrame.Box)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.toolboxp1 = QtWidgets.QWidget()
        self.toolboxp1.setGeometry(QtCore.QRect(0, 0, 141, 458))
        self.toolboxp1.setObjectName("toolboxp1")
        self.pBsmall = QtWidgets.QPushButton(self.toolboxp1)
        self.pBsmall.setGeometry(QtCore.QRect(0, 60, 140, 40))
        self.pBsmall.setObjectName("pBsmall")
        self.pBbig = QtWidgets.QPushButton(self.toolboxp1)
        self.pBbig.setGeometry(QtCore.QRect(0, 220, 140, 40))
        self.pBbig.setObjectName("pBbig")
        self.dialrotation = QtWidgets.QDial(self.toolboxp1)
        self.dialrotation.setGeometry(QtCore.QRect(40, 130, 50, 64))
        self.dialrotation.setObjectName("dialrotation")
        self.toolBox.addItem(self.toolboxp1, "")
        self.toolboxp2 = QtWidgets.QWidget()
        self.toolboxp2.setGeometry(QtCore.QRect(0, 0, 141, 458))
        self.toolboxp2.setObjectName("toolboxp2")
        self.pBpic = QtWidgets.QPushButton(self.toolboxp2)
        self.pBpic.setGeometry(QtCore.QRect(0, 0, 140, 500))
        self.pBpic.setObjectName("pBpic")
        self.toolBox.addItem(self.toolboxp2, "")
        self.groupBoxPicHLayout.addWidget(self.toolBox)

        self.graphicsView = QtWidgets.QGraphicsView(self.groupBoxPic)
        self.graphicsView.setObjectName("graphicsView")
        self.groupBoxPicHLayout.addWidget(self.graphicsView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/SVG/图片.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.partWidget.addTab(self.tabpicture, icon2, "")
        self.toolWidget = QtWidgets.QWidget()
        self.toolWidget.setObjectName("toolWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.toolWidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.toolWidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pagedanmu = QtWidgets.QWidget()
        self.pagedanmu.setObjectName("pagedanmu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pagedanmu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbprettify = QtWidgets.QLabel(self.pagedanmu)
        self.lbprettify.setObjectName("lbprettify")
        self.verticalLayout_5.addWidget(self.lbprettify)
        self.danmuHLayout = QtWidgets.QHBoxLayout()
        self.danmuHLayout.setObjectName("danmuHLayout")
        self.xmllabel = QtWidgets.QLabel(self.pagedanmu)
        self.xmllabel.setObjectName("xmllabel")
        self.danmuHLayout.addWidget(self.xmllabel)
        self.lEdanmu = QtWidgets.QLineEdit(self.pagedanmu)
        self.lEdanmu.setObjectName("lEdanmu")
        self.danmuHLayout.addWidget(self.lEdanmu)
        self.tBopen1 = QtWidgets.QToolButton(self.pagedanmu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/SVG/打开.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tBopen1.setIcon(icon3)
        self.tBopen1.setIconSize(QtCore.QSize(30, 30))
        self.tBopen1.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.tBopen1.setAutoRaise(True)
        self.tBopen1.setObjectName("tBopen1")
        self.danmuHLayout.addWidget(self.tBopen1)
        self.verticalLayout_5.addLayout(self.danmuHLayout)
        self.choiceBox = QtWidgets.QGroupBox(self.pagedanmu)
        self.choiceBox.setObjectName("choiceBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.choiceBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fontHLayout = QtWidgets.QHBoxLayout()
        self.fontHLayout.setObjectName("fontHLayout")
        self.lbsize = QtWidgets.QLabel(self.choiceBox)
        self.lbsize.setAlignment(QtCore.Qt.AlignCenter)
        self.lbsize.setObjectName("lbsize")
        self.fontHLayout.addWidget(self.lbsize)
        self.sBfontsize = QtWidgets.QSpinBox(self.choiceBox)
        self.sBfontsize.setMinimum(1)
        self.sBfontsize.setMaximum(50)
        self.sBfontsize.setProperty("value", 25)
        self.sBfontsize.setObjectName("sBfontsize")
        self.fontHLayout.addWidget(self.sBfontsize)
        self.lbfont = QtWidgets.QLabel(self.choiceBox)
        self.lbfont.setObjectName("lbfont")
        self.fontHLayout.addWidget(self.lbfont)
        self.cBfont = QtWidgets.QComboBox(self.choiceBox)
        self.cBfont.setObjectName("cBfont")
        self.cBfont.addItem("")
        self.cBfont.addItem("")
        self.cBfont.addItem("")
        self.fontHLayout.addWidget(self.cBfont)
        self.verticalLayout_7.addLayout(self.fontHLayout)
        self.sizeHLayout = QtWidgets.QHBoxLayout()
        self.sizeHLayout.setObjectName("sizeHLayout")
        self.lbwh = QtWidgets.QLabel(self.choiceBox)
        self.lbwh.setObjectName("lbwh")
        self.sizeHLayout.addWidget(self.lbwh)
        self.lEsize = QtWidgets.QLineEdit(self.choiceBox)
        self.lEsize.setObjectName("lEsize")
        self.sizeHLayout.addWidget(self.lEsize)
        self.lbopacity = QtWidgets.QLabel(self.choiceBox)
        self.lbopacity.setObjectName("lbopacity")
        self.sizeHLayout.addWidget(self.lbopacity)
        self.dsBopacity = QtWidgets.QDoubleSpinBox(self.choiceBox)
        self.dsBopacity.setMaximum(1.0)
        self.dsBopacity.setSingleStep(0.1)
        self.dsBopacity.setProperty("value", 0.8)
        self.dsBopacity.setObjectName("dsBopacity")
        self.sizeHLayout.addWidget(self.dsBopacity)
        self.verticalLayout_7.addLayout(self.sizeHLayout)
        self.velocityHLayout = QtWidgets.QHBoxLayout()
        self.velocityHLayout.setObjectName("velocityHLayout")
        self.lbvelocity = QtWidgets.QLabel(self.choiceBox)
        self.lbvelocity.setAlignment(QtCore.Qt.AlignCenter)
        self.lbvelocity.setObjectName("lbvelocity")
        self.velocityHLayout.addWidget(self.lbvelocity)
        self.sBvelocity = QtWidgets.QSpinBox(self.choiceBox)
        self.sBvelocity.setMinimum(1)
        self.sBvelocity.setMaximum(10)
        self.sBvelocity.setProperty("value", 4)
        self.sBvelocity.setObjectName("sBvelocity")
        self.velocityHLayout.addWidget(self.sBvelocity)
        self.lbstill = QtWidgets.QLabel(self.choiceBox)
        self.lbstill.setAlignment(QtCore.Qt.AlignCenter)
        self.lbstill.setObjectName("lbstill")
        self.velocityHLayout.addWidget(self.lbstill)
        self.sBstill = QtWidgets.QSpinBox(self.choiceBox)
        self.sBstill.setMinimum(1)
        self.sBstill.setMaximum(10)
        self.sBstill.setProperty("value", 5)
        self.sBstill.setObjectName("sBstill")
        self.velocityHLayout.addWidget(self.sBstill)
        self.verticalLayout_7.addLayout(self.velocityHLayout)
        self.regHLayout = QtWidgets.QHBoxLayout()
        self.regHLayout.setObjectName("regHLayout")
        self.lbreg = QtWidgets.QLabel(self.choiceBox)
        self.lbreg.setObjectName("lbreg")
        self.regHLayout.addWidget(self.lbreg)
        self.pTEreg = QtWidgets.QPlainTextEdit(self.choiceBox)
        self.pTEreg.setObjectName("pTEreg")
        self.regHLayout.addWidget(self.pTEreg)
        self.verticalLayout_7.addLayout(self.regHLayout)
        self.pBconvertdm = QtWidgets.QPushButton(self.choiceBox)
        self.pBconvertdm.setObjectName("pBconvertdm")
        self.verticalLayout_7.addWidget(self.pBconvertdm)
        self.verticalLayout_5.addWidget(self.choiceBox)
        self.lbdmto = QtWidgets.QLabel(self.pagedanmu)
        self.lbdmto.setObjectName("lbdmto")
        self.verticalLayout_5.addWidget(self.lbdmto)
        self.pTEfile = myPlainTextEdit2(self.pagedanmu)
        self.pTEfile.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.pTEfile.setObjectName("pTEfile")
        self.verticalLayout_5.addWidget(self.pTEfile)
        self.pBbegin = QtWidgets.QPushButton(self.pagedanmu)
        self.pBbegin.setObjectName("pBbegin")
        self.verticalLayout_5.addWidget(self.pBbegin)
        self.stackedWidget.addWidget(self.pagedanmu)
        self.pageVideo = QtWidgets.QWidget()
        self.pageVideo.setObjectName("pageVideo")
        self.gridLayout = QtWidgets.QGridLayout(self.pageVideo)
        self.gridLayout.setObjectName("gridLayout")
        self.combineHLayout = QtWidgets.QHBoxLayout()
        self.combineHLayout.setObjectName("combineHLayout")
        self.lbcombine = QtWidgets.QLabel(self.pageVideo)
        self.lbcombine.setAlignment(QtCore.Qt.AlignCenter)
        self.lbcombine.setObjectName("lbcombine")
        self.combineHLayout.addWidget(self.lbcombine)
        self.pBcombine = QtWidgets.QPushButton(self.pageVideo)
        self.pBcombine.setObjectName("pBcombine")
        self.combineHLayout.addWidget(self.pBcombine)
        self.gridLayout.addLayout(self.combineHLayout, 0, 0, 2, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.pageVideo)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.label_10 = myLabel(self.pageVideo)
        self.label_10.setObjectName("label_10")
        self.label_10.setAcceptDrops(True)
        self.horizontalLayout_10.addWidget(self.label_10)
        self.tBopen2 = QtWidgets.QToolButton(self.pageVideo)
        self.tBopen2.setIcon(icon3)
        self.tBopen2.setIconSize(QtCore.QSize(30, 30))
        self.tBopen2.setObjectName("tBopen2")
        self.horizontalLayout_10.addWidget(self.tBopen2)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.pageVideo)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.pageVideo)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_8.addWidget(self.lineEdit_3)
        self.label_12 = QtWidgets.QLabel(self.pageVideo)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.pageVideo)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_8.addWidget(self.lineEdit_2)
        self.cutpbbutton = QtWidgets.QPushButton(self.pageVideo)
        self.cutpbbutton.setObjectName('cutpbbutton')
        self.cutpbbutton.setText('剪切')
        self.verticalLayout_8.addWidget(self.cutpbbutton)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 1, 2, 1)
        self.plainTextEdit_4 = myPlainTextEdit(self.pageVideo)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout.addWidget(self.plainTextEdit_4, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.pageVideo)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.label_8 = myLabel(self.pageVideo)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_8.setAcceptDrops(True)
        self.horizontalLayout_9.addWidget(self.label_8)
        self.toolButton = QtWidgets.QToolButton(self.pageVideo)
        self.toolButton.setIcon(icon3)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_9.addWidget(self.toolButton)
        self.comboBox = QtWidgets.QComboBox(self.pageVideo)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.convertpbButton = QtWidgets.QPushButton(self.pageVideo)
        self.convertpbButton.setObjectName('convertpbButton')
        self.convertpbButton.setText('转码')
        self.horizontalLayout_9.addWidget(self.convertpbButton)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.pageVideo)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_22 = myLabel(self.groupBox_2)
        self.label_22.setAcceptDrops(True)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_16.addWidget(self.label_22)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_2.setIcon(icon3)
        self.toolButton_2.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_16.addWidget(self.toolButton_2)
        self.gifpbButton = QtWidgets.QPushButton(self.groupBox_2)
        self.gifpbButton.setObjectName('gifpbButton')
        self.gifpbButton.setText('导出')
        self.horizontalLayout_16.addWidget(self.gifpbButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_18.addWidget(self.lineEdit_6)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setPlaceholderText("以秒为单位")
        self.horizontalLayout_18.addWidget(self.lineEdit_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_17.addWidget(self.label_21)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_17.addWidget(self.lineEdit_5)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setMinimum(1)
        self.spinBox.setProperty("value", 15)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_17.addWidget(self.spinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.gridLayout.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 2)
        self.stackedWidget.addWidget(self.pageVideo)
        self.horizontalLayout_6.addWidget(self.stackedWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/SVG/工具.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.partWidget.addTab(self.toolWidget, icon4, "")
        self.tabAnli = QtWidgets.QWidget()
        self.tabAnli.setObjectName("tabAnli")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabAnli)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbanli = QtWidgets.QLabel(self.tabAnli)
        self.lbanli.setText("")
        self.lbanli.setPixmap(QtGui.QPixmap(":/PNG/tlj2.png"))
        self.lbanli.setScaledContents(True)
        self.lbanli.setObjectName("lbanli")
        self.verticalLayout_4.addWidget(self.lbanli)
        self.tBTnote = QtWidgets.QTextBrowser(self.tabAnli)
        self.tBTnote.setOpenExternalLinks(True)
        self.tBTnote.setObjectName("tBTnote")
        self.verticalLayout_4.addWidget(self.tBTnote)
        self.verticalLayout_4.setStretch(0, 4)
        self.verticalLayout_4.setStretch(1, 3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/SVG/说明.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.partWidget.addTab(self.tabAnli, icon5, "")
        self.centralVLayout.addWidget(self.partWidget)
        self.centralHLayout0.addLayout(self.centralVLayout)
        iconk = QtGui.QIcon()
        iconk.addPixmap(QtGui.QPixmap(":/JPG/口袋48.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newpage = QtWidgets.QWidget()
        self.newpage.setObjectName("newpage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.newpage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newLB = QtWidgets.QLabel(self.newpage)
        self.newLB.setObjectName("newLB")
        self.gridLayout_2.addWidget(self.newLB, 0, 0, 1, 1)
        self.newLE = QtWidgets.QLineEdit(self.newpage)
        self.newLE.setObjectName("newLE")
        self.gridLayout_2.addWidget(self.newLE, 0, 1, 1, 1)
        self.newPB = QtWidgets.QPushButton(self.newpage)
        self.newPB.setObjectName("newPB")
        self.gridLayout_2.addWidget(self.newPB, 0, 2, 1, 1)
        self.newPG = QtWidgets.QProgressBar(self.newpage)
        self.newPG.setProperty("value", 0)
        self.newPG.setObjectName("newPG")
        self.gridLayout_2.addWidget(self.newPG, 1, 0, 1, 3)
        self.newTB = QtWidgets.QTextBrowser(self.newpage)
        self.newTB.setOpenExternalLinks(True)
        self.newTB.setObjectName("newTB")
        self.gridLayout_2.addWidget(self.newTB, 2, 0, 1, 3)
        self.partWidget.addTab(self.newpage, iconk, "")
        myWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(myWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        myWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(myWindow)
        self.statusbar.setObjectName("statusbar")
        myWindow.setStatusBar(self.statusbar)
        self.actionsave = QtWidgets.QAction(myWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/SVG/保存文件.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave.setIcon(icon6)
        self.actionsave.setObjectName("actionsave")
        self.actionrecycle = QtWidgets.QAction(myWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/SVG/中间文件.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionrecycle.setIcon(icon7)
        self.actionrecycle.setObjectName("actionrecycle")
        self.actionxp = QtWidgets.QAction(myWindow)
        self.actionxp.setObjectName("actionxp")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/SVG/xp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionxp.setIcon(icon8)
        self.actionxp.triggered.connect(myWindow.handlestyle)
        self.actionwindows = QtWidgets.QAction(myWindow)
        self.actionwindows.setObjectName("actionwindows")
        icon86 = QtGui.QIcon()
        icon86.addPixmap(QtGui.QPixmap(":/SVG/windows.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionwindows.setIcon(icon86)
        self.actionwindows.triggered.connect(myWindow.handlestyle)
        self.actionfusion = QtWidgets.QAction(myWindow)
        self.actionfusion.setObjectName("actionfusion")
        icon81 = QtGui.QIcon()
        icon81.addPixmap(QtGui.QPixmap(":/SVG/fusion.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfusion.setIcon(icon81)
        self.actionfusion.triggered.connect(myWindow.handlestyle)
        self.actionconvert = QtWidgets.QAction(myWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/SVG/工具切换.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionconvert.setIcon(icon9)
        self.actionconvert.setObjectName("actionconvert")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/SVG/播放.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen_2 = QtWidgets.QAction(myWindow)
        self.actionopen_2.setObjectName("actionopen_2")
        self.actionopen_2.setIcon(icon10)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionrecycle)
        self.menu.addSeparator()
        self.menu.addAction(self.actionconvert)
        self.menu.addSeparator()
        self.menu_3.addAction(self.actionxp)
        self.menu_3.addAction(self.actionwindows)
        self.menu_3.addAction(self.actionfusion)
        self.menu_2.addAction(self.actionopen_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.actionsave.triggered.connect(myWindow.diropen)
        self.actionrecycle.triggered.connect(myWindow.diropen)
        self.actionconvert.triggered.connect(myWindow.partVD)
        self.actionopen_2.triggered.connect(myWindow.vopen)
        self.myclipboard = QtWidgets.QApplication.clipboard()
        self.myclipboard.dataChanged.connect(myWindow.tpaste)
        self.okPushButton.clicked.connect(myWindow.start_info)
        self.partWidget.currentChanged[int].connect(myWindow.videobar_show)
        self.pBcombine.clicked.connect(myWindow.combinev)
        self.tBopen2.clicked.connect(myWindow.openf)
        self.cutpbbutton.clicked.connect(myWindow.cutst)
        self.toolButton.clicked.connect(myWindow.openf)
        self.convertpbButton.clicked.connect(myWindow.convertto)
        self.gifpbButton.clicked.connect(myWindow.gifdo)
        self.pushButtonAllDownLoad.clicked.connect(myWindow.downloadall)
        self.tBopen1.clicked.connect(myWindow.openf)
        self.toolButton_2.clicked.connect(myWindow.openf)
        self.pBconvertdm.clicked.connect(myWindow.prettifydanmu)
        self.pBbegin.clicked.connect(myWindow.danmutov)
        self.newPB.clicked.connect(myWindow.dkoudai)
        self.pBsmall.clicked.connect(myWindow.smallerp)
        self.pBbig.clicked.connect(myWindow.bigp)
        self.dialrotation.valueChanged[int].connect(myWindow.rotationp)
        self.pBpic.clicked.connect(myWindow.downloadp)
        self.retranslateUi(myWindow)
        self.initialfile()
        self.partWidget.setCurrentIndex(4)
        self.toolBox.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(myWindow)

    def retranslateUi(self, myWindow):
        _translate = QtCore.QCoreApplication.translate
        myWindow.setWindowTitle(_translate("myWindow", "TTDd"))
        self.labelBV.setText(_translate("myWindow", "BV号输入"))
        self.okPushButton.setText(_translate("myWindow", "确定"))
        item = self.infoChart.verticalHeaderItem(0)
        item.setText(_translate("myWindow", "AV"))
        item = self.infoChart.verticalHeaderItem(1)
        item.setText(_translate("myWindow", "标题"))
        item = self.infoChart.verticalHeaderItem(2)
        item.setText(_translate("myWindow", "作者"))
        item = self.infoChart.verticalHeaderItem(3)
        item.setText(_translate("myWindow", "分p数"))
        item = self.infoChart.verticalHeaderItem(4)
        item.setText(_translate("myWindow", "播放数"))
        item = self.infoChart.verticalHeaderItem(5)
        item.setText(_translate("myWindow", "弹幕数"))
        item = self.infoChart.verticalHeaderItem(6)
        item.setText(_translate("myWindow", "尺寸"))
        item = self.infoChart.horizontalHeaderItem(0)
        item.setText(_translate("myWindow", "New Column"))
        self.labelDesc.setText(_translate("myWindow", "描述"))
        self.partWidget.setTabText(self.partWidget.indexOf(self.tabInfo), _translate("myWindow", "信息"))
        self.radButtonXML.setText(_translate("myWindow", "弹幕XML"))
        self.radButtonASS.setText(_translate("myWindow", "弹幕ASS"))
        self.radButtonASS.setAutoExclusive(False)
        self.radButtonASS.setChecked(False)
        self.radButtonXML.setAutoExclusive(False)
        self.radButtonXML.setChecked(False)
        self.labelThreads.setText(_translate("myWindow", "线程数"))
        self.pushButtonAllDownLoad.setText(_translate("myWindow", "全部下载"))
        self.partWidget.setTabText(self.partWidget.indexOf(self.tabVideo), _translate("myWindow", "视频"))
        self.groupBoxPic.setTitle(_translate("myWindow", "PICTURE"))
        self.pBsmall.setText(_translate("myWindow", "缩小"))
        self.pBbig.setText(_translate("myWindow", "放大"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolboxp1), _translate("myWindow", "   操作"))
        self.pBpic.setText(_translate("myWindow", "下载"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolboxp2), _translate("myWindow", "   获取"))
        self.partWidget.setTabText(self.partWidget.indexOf(self.tabpicture), _translate("myWindow", "图片"))
        self.lbprettify.setText(_translate("myWindow", "<html><head/><body><p>弹幕美化</p></body></html>"))
        self.xmllabel.setText(_translate("myWindow", "xml弹幕文件"))
        self.lEdanmu.setPlaceholderText(_translate("myWindow", "D:\\B站视频"))
        self.tBopen1.setText(_translate("myWindow", "..."))
        self.choiceBox.setTitle(_translate("myWindow", "选项框"))
        self.lbsize.setText(_translate("myWindow", "<html><head/><body><p>字体大小</p></body></html>"))
        self.lbfont.setText(_translate("myWindow", "<html><head/><body><p align=\"center\">字体</p></body></html>"))
        self.cBfont.setItemText(0, _translate("myWindow", "simsunb"))
        self.cBfont.setItemText(1, _translate("myWindow", "Microsoft YaHei"))
        self.cBfont.setItemText(2, _translate("myWindow", "FangSong"))
        self.lbwh.setText(_translate("myWindow", "长x宽"))
        self.lEsize.setPlaceholderText(_translate("myWindow", "例如:1024x960"))
        self.lbopacity.setText(_translate("myWindow", "透明度"))
        self.lbvelocity.setText(_translate("myWindow", "弹幕滚动速度"))
        self.lbstill.setText(_translate("myWindow", "停留弹幕时间"))
        self.lbreg.setText(_translate("myWindow", "弹幕正则过滤"))
        self.pTEreg.setPlaceholderText(_translate("myWindow", "例如:[0-9]*"))
        self.pBconvertdm.setText(_translate("myWindow", "美化"))
        self.lbdmto.setText(_translate("myWindow", "<html><head/><body><p>弹幕烧录(ass,srt)</p></body></html>"))
        self.pTEfile.setPlaceholderText(_translate("myWindow", "拖拽文件于此处"))
        self.pBbegin.setText(_translate("myWindow", "烧录"))
        self.lbcombine.setText(_translate("myWindow", "合并视频"))
        self.pBcombine.setText(_translate("myWindow", "开始"))
        self.label_9.setText(_translate("myWindow", "剪切|"))
        self.label_10.setText(_translate("myWindow", "打开文件于此处"))
        self.tBopen2.setText(_translate("myWindow", "..."))
        self.label_11.setText(_translate("myWindow", "起始时间"))
        self.lineEdit_3.setPlaceholderText(_translate("myWindow", "hour.minutes.second"))
        self.label_12.setText(_translate("myWindow", "结束时间"))
        self.lineEdit_2.setPlaceholderText(_translate("myWindow", "hour.minutes.second"))
        self.plainTextEdit_4.setPlaceholderText(_translate("myWindow", "拖拽文件到此处..."))
        self.label_7.setText(_translate("myWindow", "        转码        |"))
        self.label_8.setText(_translate("myWindow", "打开文件于此处"))
        self.toolButton.setText(_translate("myWindow", "..."))
        self.comboBox.setItemText(0, _translate("myWindow", "mp4"))
        self.comboBox.setItemText(1, _translate("myWindow", "flv"))
        self.comboBox.setItemText(2, _translate("myWindow", "mpeg"))
        self.groupBox_2.setTitle(_translate("myWindow", "GIF"))
        self.label_22.setText(_translate("myWindow", "(文件名最好改为字母和数字)打开文件于此处"))
        self.toolButton_2.setText(_translate("myWindow", "..."))
        self.label_24.setText(_translate("myWindow", "起始时间"))
        self.label_25.setText(_translate("myWindow", "持续时间"))
        self.label_21.setText(_translate("myWindow", "图像大小"))
        self.lineEdit_5.setPlaceholderText(_translate("myWindow", "例如:300x400"))
        self.label_23.setText(_translate("myWindow", "帧率"))
        self.partWidget.setTabText(self.partWidget.indexOf(self.toolWidget), _translate("myWindow", "工具"))
        self.tBTnote.setHtml(_translate("myWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">说明</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">1.目前暂时不支持番剧,会员,互动视频下载(或许会在后续版本补充)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">2.计划补充微博相关功能,包括数据统计,视频和图片的批量下载</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">3.风格按钮可以切换窗口样式,默认为fusion样式</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">4.打开菜单栏的播放功能仅供视频预览,不支持快进.且有时需要 Alt+F4 才能退出</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">5.对于下载比较大的视频,比如超过50分钟的游戏录播或者纪录片.可以调高线程数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">欢迎关注</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">1.</span><a href=\"https://space.bilibili.com/14574654\"><span style=\" font-family:\'SimSun\'; text-decoration: underline; color:#0000ff;\">作者B站主页</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">1.</span><a href=\"https://weibo.com/5542757479\"><span style=\" font-family:\'SimSun\'; text-decoration: underline; color:#0000ff;\">作者微博主页</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">2.</span><a href=\"https://space.bilibili.com/290472920\"><span style=\" font-family:\'SimSun\'; text-decoration: underline; color:#0000ff;\">黑夜女神之神</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">3.</span><a href=\"https://weibo.com/u/5885940120\"><span style=\" font-family:\'SimSun\'; text-decoration: underline; color:#0000ff;\">GNZ48-唐莉佳微博</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-weight:600;\"><br /></p></body></html>"))
        self.partWidget.setTabText(self.partWidget.indexOf(self.tabAnli), _translate("myWindow", "说明"))
        self.menu.setTitle(_translate("myWindow", "设置"))
        self.menu_3.setTitle(_translate("myWindow", "风格"))
        self.menu_2.setTitle(_translate("myWindow", "打开"))
        self.actionsave.setText(_translate("myWindow", "保存文件"))
        self.actionrecycle.setText(_translate("myWindow", "中间文件"))
        self.actionxp.setText(_translate("myWindow", "XP"))
        self.actionwindows.setText(_translate("myWindow", "WINDOWS"))
        self.actionfusion.setText(_translate("myWindow", "FUSION"))
        self.actionconvert.setText(_translate("myWindow", "工具切换"))
        self.actionopen_2.setText(_translate("myWindow", "播放"))
        self.newLB.setText(_translate("myWindow", "连接"))
        self.newPB.setText(_translate("myWindow", "下载"))
        self.newTB.setHtml(_translate("myWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">使用方法</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">1.在口袋48app将视频分享到微博</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">2.点开微博分享连接,将弹出一个新窗口例如:</span><a href=\"https://h5.48.cn/2019appshare/memberLiveShare/?id=455489351445188608\"><span style=\" font-family:\'SimSun\'; text-decoration: underline; color:#0000ff;\">点我</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">3.复制此新窗口的网址</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">4.将网址黏贴到连接输入框</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"TLJ.png\" /></p></body></html>"))
        self.partWidget.setTabText(self.partWidget.indexOf(self.newpage), _translate("myWindow", "口袋"))
    def initialfile(self):
        self.filesave = './video';self.filerec = './temp'
import res_rc